### ISSUE TITLE
Reinforced Enemy Facilities units spawn in exactly the same place as previous wreck.

### ISSUE THREAD

**Issue by ozdeadmeat** [Dzsek/zoneCommander#7]
Issue: After killing some units in a capture zone and the enemy helicopter the resupplies facility, the destroyed units are respawned in exactly the same place as the previous unit. This makes finding the targets that are actually alive very difficult as they are obsured by the wreck of the previous unit.

Possible Solution:
Per Unit have a small randomizer value of 200 - 500ft for X and Y axis.

**Comment by Dzsek** [comment]
Its a known issue, that happens when a group was not completely destroyed.
The problem is that mist can only respawn the whole group, not individual units.

So the two options are either respawn the whole group in a different position, which causes existing units to jump around, or respawn the group in the same position, overlapping previously destroyed units with their wrecks.

The second options was chosen, because relocating the whole group feels like a worse solution

**Comment by DrTeemo** [comment]
would it be possible to delete the remnant of the previous group, and then replace it with a new one?

**Comment by Dzsek** [comment]
Dcs does not let you remove wrecks at the moment.

**Comment by ozdeadmeat** [comment]
Or dont use Mist to spawn units / groups?
